# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/sm8250-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter bitra RMX3371,$(TARGET_DEVICE)),)

endif
